export const CHECK_AUTH_CODE_REQUEST = 'CHECK_AUTH_CODE_REQUEST';
export const CHECK_AUTH_CODE_SUCCESS = 'CHECK_AUTH_CODE_SUCCESS';
export const CHECK_AUTH_CODE_FAILURE = 'CHECK_AUTH_CODE_FAILURE';
export const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';
export const AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED';
export const LOG_OUT = 'LOG_OUT';


export const FETCH_AUTH_CODE_REQUEST = 'FETCH_AUTH_CODE_REQUEST';
export const FETCH_AUTH_CODE_SUCCESS = 'FETCH_AUTH_CODE_SUCCESS';
export const FETCH_AUTH_CODE_FAILURE = 'FETCH_AUTH_CODE_FAILURE';