export const FETCH_PRODUCTS_REQUEST:string = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS:string = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE:string = 'FETCH_PRODUCTS_FAILURE';
export const PRODUCTS_LIST_RESET:string = 'PRODUCTS_LIST_RESET';
