export const FETCH_PRODUCT_REQUEST:string = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS:string = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE:string = 'FETCH_PRODUCT_FAILURE';
export const PRODUCT_RESET:string = 'PRODUCT_RESET';
