export const FETCH_USERS_REQUEST:string = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS:string = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE:string = 'FETCH_USERS_FAILURE';
export const USERS_LIST_RESET:string = 'USERS_LIST_RESET';
